import Head from "next/head";

const Layout = ({ children }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="container mx-auto py-4">
        <h1 className="text-3xl">
          <a href="/"> The Art of Legends of Runeterra</a>
        </h1>
      </nav>
      <main className="container mx-auto">{children}</main>
      <footer className="container mx-auto py-4">
        <p className="text-xs">© 2022 The Art of Legends of Runeterra.</p>
      </footer>
    </div>
  );
};

export default Layout;
